gcp_project_id = "alation-assignment"
service_account_email = "519881645595-compute@developer.gserviceaccount.com"
region =  "asia-south1"
zone = "asia-south1-a"
vm_name = "alation-miniqube-k8s-cluster"
vm_type = "e2-standard-2"
vm_image = "ubuntu-os-cloud/ubuntu-2004-focal-v20221121"
vm_image_type = "pd-standard"
